### ISSUE TITLE
Intégrer CoreNLP et récupérer les objets clefs d'une phrase

### ISSUE THREAD

**Issue by Dorpaxio** [TERinou/Brain#1]

**Comment by KGM-KGM** [comment]
https://www.npmjs.com/package/corenlp

**Comment by KGM-KGM** [comment]
Mise en place de NodeNLP à la place de CoreNLP
https://www.npmjs.com/package/node-nlp

**Comment by KGM-KGM** [comment]
https://www.npmjs.com/package/nlp-js-tools-french
